apiVersion: barbican.openstack.org/v1beta1
kind: BarbicanAPI
metadata:
  name: barbican
  labels:
    app.kubernetes.io/name: barbicanapi
    app.kubernetes.io/instance: barbicanapi-sample
    app.kubernetes.io/part-of: barbican-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: barbican-operator
  name: barbicanapi-sample
spec:
  serviceUser: barbican
  containerImage: quay.io/tripleozedcentos9/openstack-barbican:current-tripleo
  apiType: external
  replicas: 1
  customServiceConfig: |
    [DEFAULT]
    debug = True
  # databaseHostname:
  databaseUser: barbican
  databaseInstance: openstack
  secret: barbican-secret
  passwordSelectors:
	# TODO(dmendiza): What does the selector look like?
  nodeSelector:
	# TODO(dmendiza): What does this look like?
  debug:
	# TODO(dmendiza): This is k8s level debugging ... what is the default here?
  defaultConfigOverwrite:
	# TODO(dmendiza): Add sample here when implemented.
  networkAttachments:
	# TODO(dmendiza): Add sample here when implemented.
  externalEndpoints:
	# TODO(dmendiza): Add sample here when implemented.
